/* create and insert passports table */
CREATE TABLE IF NOT EXISTS passports (
  "id" INT GENERATED BY DEFAULT AS IDENTITY
  	(START WITH 100 INCREMENT BY 1) PRIMARY KEY,
  nationality VARCHAR(50)
);

INSERT INTO passports (nationality) 
VALUES
	('N34FG41B'),
	('K65LF4R7'),
	('ZE357QP2');

/* b. create and insert people table */
CREATE TABLE IF NOT EXISTS people (
  "id" SERIAL PRIMARY KEY,
  first_name VARCHAR(50),
	salary NUMERIC(10, 2),
  passport_id INT,
	CONSTRAINT fk_people_passports
		FOREIGN KEY (passport_id) 
		REFERENCES passports("id")
);

INSERT INTO people (first_name, salary, passport_id) 
VALUES
	('Roberto', 43200.00, 101),
	('Tomi', 56200.00, 102),
	('Yanka', 61200.00, 100);
