/* create tables */
CREATE TABLE IF NOT EXISTS manufacturers (
  "id" SERIAL PRIMARY KEY,
  name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS models (
  "id" INT GENERATED BY DEFAULT AS IDENTITY
  	(START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
  model_name VARCHAR(50),
	manufacturer_id INT,
	CONSTRAINT fk_models_manufacturers
		FOREIGN KEY (manufacturer_id) 
		REFERENCES manufacturers("id")
);

CREATE TABLE IF NOT EXISTS production_years (
  "id" SERIAL PRIMARY KEY,
	established_on DATE NOT NULL,
	manufacturer_id INT,
	CONSTRAINT fk_production_years_manufacturers
		FOREIGN KEY (manufacturer_id) 
		REFERENCES manufacturers("id")
);
