/* students table */
CREATE TABLE IF NOT EXISTS students (
  "id" SERIAL PRIMARY KEY,
  student_name VARCHAR(50)
);

INSERT INTO students (student_name) 
VALUES
	('Mila'),
	('Toni'),
	('Ron');

/* exams table */
CREATE TABLE IF NOT EXISTS exams (
  "id" INT GENERATED BY DEFAULT AS IDENTITY
  	(START WITH 101 INCREMENT BY 1) PRIMARY KEY,
  exam_name VARCHAR(50)
);

INSERT INTO exams (exam_name) 
VALUES
	('Python Advanced'),
	('Python OOP'),
	('PostgreSQL');
	