/* students table */
CREATE TABLE IF NOT EXISTS students (
  "id" SERIAL PRIMARY KEY,
  student_name VARCHAR(50)
);

INSERT INTO students (student_name) 
VALUES
	('Mila'),
	('Toni'),
	('Ron');

/* exams table */
CREATE TABLE IF NOT EXISTS exams (
  "id" INT GENERATED BY DEFAULT AS IDENTITY
  	(START WITH 101 INCREMENT BY 1) PRIMARY KEY,
  exam_name VARCHAR(50)
);

INSERT INTO exams (exam_name) 
VALUES
	('Python Advanced'),
	('Python OOP'),
	('PostgreSQL');
	
/* study halls table */
CREATE TABLE IF NOT EXISTS study_halls (
  "id" SERIAL PRIMARY KEY,
  study_hall_name VARCHAR(50),
	exam_id INT,
	CONSTRAINT fk_students_halls_exams
		FOREIGN KEY(exam_id)
		REFERENCES exams("id")
);

INSERT INTO study_halls (study_hall_name, exam_id) 
VALUES
	('Open Source Hall', 102),
	('Inspiration Hall', 101),
	('Creative Hall', 103),
	('Masterclass Hall', 103),
	('Information Security Hall', 103);
